### ISSUE TITLE
JA4S and JA4X discrepancies between Rust and Python version

### ISSUE THREAD

**Issue by john-althouse** [FoxIO-LLC/ja4#11]
![image](https://github.com/FoxIO-LLC/ja4/assets/84981330/03e0314e-6c17-4b86-bddc-6516ca91cf53)

In the above screenshot we're looking at Stream 0 on https://github.com/FoxIO-LLC/ja4/blob/main/pcap/browsers-x509.pcapng

The python version is not parsing out the ALPN in JA4S.
The rust version is not parsing out the JA4X for that stream.

**Comment by vvv** [comment]
Rust code didn't expect "Server Hello" and "Certificate" layers to be present in the same packet.

![Wireshark UI shows that `frame.number == 8` has "Server Hello" and "Certificate" layers](https://github.com/FoxIO-LLC/ja4/assets/17462/ac18c7b4-b83a-4e03-85b4-4a8b7f75df06)

**Comment by john-althouse** [comment]
All fixed!
