### ISSUE TITLE
Inconsistent JA4H fingerprint regarding referer and cookie fields

### ISSUE THREAD

**Issue by axmahr** [FoxIO-LLC/ja4#113]
Hi!

I ran your tools on the [attached pcap file here](https://github.com/FoxIO-LLC/ja4/files/15406024/http-with-referer.zip) and got different fingerprints for the Python and Rust version (I didn't test the other implementations).
The Rust tool yields the JA4H fingerprint `ge11cr08en00_2875ece69b0a_bd267b3dba1e_c167a8c34cde` (which I think is the intended one) and the Python tool outputs `ge11cn08en00_2875ece69b0a_87137639f479_c167a8c34cde`.

There are two differences:
- The Python version does not recognize the Referer field, although it is set in the HTTP request. I think that is because the corresponding check for the `referer`-string is run on the complete header fields including the value parts:
https://github.com/FoxIO-LLC/ja4/blob/3fe3b5b67a84f34ce36fc3f76ab4cc9a5d126b20/python/ja4h.py#L18
- The calculated hash for the sorted cookie fields `JA4H_c` is different for the Python version. I think that is because, looking into the implementation, `x['cookie_fields']` is set to `[' n', 'd']` with this pcap file. Notice the space in front of `n`.

**Comment by noeltimothy** [comment]
Added a fix here https://github.com/FoxIO-LLC/ja4/pull/122
