### ISSUE TITLE
JA4X for Python crashes with one Extension 

### ISSUE THREAD

**Issue by axmahr** [FoxIO-LLC/ja4#114]
Hi!

The [attached pcap file here ](https://github.com/FoxIO-LLC/ja4/files/15406428/one-extension.zip) contains a certificate with only one extension. This crashes the python implementation here: https://github.com/FoxIO-LLC/ja4/blob/9f884cf6f16f4d30ef540ab1ccd1645132a8bb04/python/ja4x.py#L78-L82
`x['cert_extensions']` is expected to be a list. However, it is a string when the certificate contains only one extension.

**Comment by noeltimothy** [comment]
This has been fixed and merged.
