### ISSUE TITLE
No ja4 output using Zeek

### ISSUE THREAD

**Issue by CopyOfA** [FoxIO-LLC/ja4#142]
I've added ja4 directory (shown here: https://github.com/FoxIO-LLC/ja4/tree/main/zeek) to /opt/zeek/share/zeek/site as `ja4plus`. I've also added the line `@load ja4plus` to the end of my `local.zeek` file. When I run `zeek -r mypcap.pcap`, there are no ja4 fingerprints in any of the Zeek output files. I've also tried `zkg install zeek/foxio/ja4`, and still getting no ja4 output. I'm not sure that this is necessarily an Issue, but I can't figure out why I'm not getting output. I'm running Zeek version 7.0.0 on Ubuntu 22.04; could this be the problem?

**Comment by harleyh** [comment]
I'm having the same issue on Fedora 40. Oddly, I saw JA4 output in logs yesterday but am not seeing them this morning. And, as far as I can remember nothing has changed. `zeekctl scripts` is showing the JA4 scripts are loaded:
```
$ zeekctl scripts|grep ja4
    /opt/zeek/share/zeek/site/ja4plus/__load__.zeek
      /opt/zeek/share/zeek/site/ja4plus/config.zeek
      /opt/zeek/share/zeek/site/ja4plus/ja4/__load__.zeek
        /opt/zeek/share/zeek/site/ja4plus/utils/common.zeek
        /opt/zeek/share/zeek/site/ja4plus/utils/ssl-consts.zeek
        /opt/zeek/share/zeek/site/ja4plus/ja4/helpers.zeek
        /opt/zeek/share/zeek/site/ja4plus/ja4/main.zeek
      /opt/zeek/share/zeek/site/ja4plus/ja4s/__load__.zeek
        /opt/zeek/share/zeek/site/ja4plus/ja4s/main.zeek
      /opt/zeek/share/zeek/site/ja4plus/ja4h/__load__.zeek
        /opt/zeek/share/zeek/site/ja4plus/ja4h/main.zeek
      /opt/zeek/share/zeek/site/ja4plus/ja4ssh/__load__.zeek
        /opt/zeek/share/zeek/site/ja4plus/ja4ssh/main.zeek
      /opt/zeek/share/zeek/site/ja4plus/ja4x/__load__.zeek
      /opt/zeek/share/zeek/site/ja4plus/ja4t/__load__.zeek
        /opt/zeek/share/zeek/site/ja4plus/ja4t/main.zeek
```

I'm also still on Zeek 6.0.5 at the moment.

**Comment by john-althouse** [comment]
@harleyh Are there any errors? There's been no change to the JA4+ code... 
@CopyOfA , Zeek doesn't load your local.zeek when you're reading pcap, try calling it manually by doing something like `zeek -r mypcap.pcap /opt/bin/zeek/user/zeek/site/local.zeek` or `zeek -r mypcap.pcap local`

**Comment by john-althouse** [comment]
I've done the same thing multiple times. Great to hear its working now!

**Comment by CopyOfA** [comment]
Yes, this solved my problem. I did not know that I needed point zeek to my local.zeek file. Since doing that everything works as expected. Thanks!
