### ISSUE TITLE
Question about JA4 fingerprint without signature algorithms

### ISSUE THREAD

**Issue by p-l-** [FoxIO-LLC/ja4#146]
Hi there :wave:

While implementing JA4 fingerprint for [IVRE](https://github.com/ivre/ivre) (ivre/ivre#1633, ivre/ivre#1634) and looking at other implementations ([Fingerproxy](https://github.com/wi1dcard/fingerproxy)), I came across something that is not clear (for me), and I would like to make sure I have the correct answer.

The last part of the JA4 fingerprint ("JA4_c") is a truncated sha256 hash of the list of sorted extensions, then `_`, then the list of signature algorithms, in the order they appear.

My question is, what happens when there is no signature algorithms? Should we include a trailing underscore in the value we hash? That's what does the Zeek implementation from this repository ([code](https://github.com/FoxIO-LLC/ja4/blob/a0b8a3e13c1b95a2e2e02a8a0cf0176691e3c2bd/zeek/ja4/main.zeek#L149-L152)), or should we not include that hash? That's what do the Python implementation from this repository ([code](https://github.com/FoxIO-LLC/ja4/blob/a0b8a3e13c1b95a2e2e02a8a0cf0176691e3c2bd/python/ja4.py#L225-L230)) and Fingerproxy ([code](https://github.com/wi1dcard/fingerproxy/blob/0a25fd378240abfa905194dcc5c33c283fb8a91a/pkg/ja4/ja4.go#L96-L100)).

Also, even if that looks like a dumb question, what should we do when no extension at all is seen? In that case, the signature algorithms list is empty. Should we hash the empty string? Or a single underscore?

IMO it would be better to always include the separator `_` (cleaner code, and avoids possible confusion), but in any cases the decision should be made super clear (and the implementations in this repository should be fixed so that they are consistent). Apologizes if that's already the case and I missed it.

**Comment by lrstewart** [comment]
The [technical details](https://github.com/FoxIO-LLC/ja4/blob/main/technical_details/JA4.md#extension-hash) do say:
> If there are no signature algorithms in the hello packet, then the string ends without an underscore and is hashed.

**Comment by p-l-** [comment]
Oh thanks a lot @lrstewart!
