### ISSUE TITLE
Wireshark JA4+ Plugin does not work with version 4.4

### ISSUE THREAD

**Issue by john-althouse** [FoxIO-LLC/ja4#155]

**Comment by skander72** [comment]
Please support this version of wireshark (v4.4) as it is the current version (easier to install) on Arch Linux (with termshark and other  pcap analysis CLI tools built on its libraries).

**Comment by igr001-galactica** [comment]
We just released Wireshark plugins for Wireshark 4.4 for Linux, Windows, and Mac. Let us know if you run into any issues.
