### ISSUE TITLE
Handling of headers in JA4H

### ISSUE THREAD

**Issue by s-spindler** [FoxIO-LLC/ja4#172]
Hi!

Regarding the number of headers field in JA4H_a; how should an implementation handle values <10 and >99?

Based on the [spec for the number of ciphers in JA4](https://github.com/FoxIO-LLC/ja4/blob/bc1806c0e5c44c78863d11b8e589faa9954e9eed/technical_details/JA4.md?plain=1#L55) I assume the value is 0-padded for a count <10 and truncated to last 2 digits for count >99. Is that correct?

**Comment by s-spindler** [comment]
Addendum: if my assumption above is correct, the Python implementation does not limit to max 99. I prepared #173 with a suggested fix.

**Comment by john-althouse** [comment]
You are correct!

**Comment by s-spindler** [comment]
Since #173 is merged this can be closed. Feel free to reopen in case you think there's something missing!
