### ISSUE TITLE
JA4H.md Cookie Values SHA256 Error

### ISSUE THREAD

**Issue by idlefire** [FoxIO-LLC/ja4#20]
```
1P_JAR=2023-06-07-17,AEC=AUEFqZdaLLwaXJHyxA8-Cu0i0N4klp_vV3XOuyEYeiWlp4QaeIvSv6t4XKM,DV=A84BtBIPqhgmIDlq9acmfs7ik-duiZjdmUPDG3eW3QIAAAA,NID=511=rRELE2o91XNLo6eayqEN7Lf2ue7EcSHVkew3oxf4jzyF8vix2BzxTRvda8MYBFEkLyC1xjTcqSIjbC-wV2r120jr2HFau_dHvMxUm9fk6W2J2mddtlMpGMA8qGuAZWt1DSpCFFwHZSKBryGnvRJUeXkc-jw4sXdWhgCKxeu3f01Na4YsBYGf,OGPC=19027681-1:

Sha256: e97928733c7408285e0878640b946867e0a8fd0ac02765ad48a375220296a5e3
Truncated: e97928733c74
```

There is an extra ":" at the end of the calculation sha256
The correct sha256 is `3bdbfcbc2e9e4c7a0b51de3efa7578fe1a54d09d0771d702eebdc1bb0ca438a3`

**Comment by john-althouse** [comment]
The ":" is part of that cookie field value so it would remain. The only characters in the cookie we are replacing are the ";" cookie field delimiters. Does that make sense?

**Comment by idlefire** [comment]
Thank you for your answer. I didn't find ":" in the original cookie, so I thought ":" was added by mistake. Thanks again
