### ISSUE TITLE
JA4 of Chrome (ECH)

### ISSUE THREAD

**Issue by fwilliamhe** [FoxIO-LLC/ja4#31]
The TLS extension `padding` may appear due to the packet size. And the JA4 of this case is `[JA4: t13d1517h2_8daaf6152771_b1ff8ab2d16f]`
Chrome : Version 120.0.6099.71 (Official Build) (64-bit)
The source code of BoringSSL can also prove it.
```cpp
static bool setup_ech_grease(SSL_HANDSHAKE *hs) {
 // ... 
  const size_t payload_len =
      32 * random_size(128 / 32, 224 / 32) + aead_overhead(aead);
  bssl::ScopedCBB cbb;
  CBB enc_cbb, payload_cbb;
  uint8_t *payload;
  if (!CBB_init(cbb.get(), 256) ||
      !CBB_add_u16(cbb.get(), kdf_id) ||
      !CBB_add_u16(cbb.get(), EVP_HPKE_AEAD_id(aead)) ||
      !CBB_add_u8(cbb.get(), config_id) ||
      !CBB_add_u16_length_prefixed(cbb.get(), &enc_cbb) ||
      !CBB_add_bytes(&enc_cbb, enc, sizeof(enc)) ||
      !CBB_add_u16_length_prefixed(cbb.get(), &payload_cbb) ||
      !CBB_add_space(&payload_cbb, &payload, payload_len) ||
      !RAND_bytes(payload, payload_len) ||
      !CBBFinishArray(cbb.get(), &hs->ech_client_outer)) {
    return false;
  }
  return true;
}
```

**Comment by vvv** [comment]
@fwilliamhe Thanks for the feedback.

1. Please help me understand what exactly is not right.
   i. Is it [JA4 specification](https://github.com/FoxIO-LLC/ja4/blob/f6a1aaa366c964502d0beef17d48e6c7b1aba20d/technical_details/JA4.md)?
   ii. [Python application](https://github.com/FoxIO-LLC/ja4/tree/f6a1aaa366c964502d0beef17d48e6c7b1aba20d/python)?
   iii. [Wireshark plugin](https://github.com/FoxIO-LLC/ja4/tree/f6a1aaa366c964502d0beef17d48e6c7b1aba20d/wireshark)?
   iv. [Rust application](https://github.com/FoxIO-LLC/ja4/tree/f6a1aaa366c964502d0beef17d48e6c7b1aba20d/rust/ja4)?
2. Do you have any capture file that can be used to reproduce the problem?

**Comment by fwilliamhe** [comment]
The JA4+ Fingerprints of Google Chrome or Chromium (ECH) can be [JA4: t13d1517h2_8daaf6152771_b1ff8ab2d16f], which is different from the one showed in README. 
This happens very rarely and I forgot to save the capture file yesterday. I will try to reproduce it as soon as possible.

As far as I know, this situation happens when no `ECH_Config_List` is given to the SSL socket (Usually because the target server doesn't support ECH) and `ECH_GREASE` will be enabled according to the source of Chromium ([`net/socket/ssl_client_socket_impl.cc:906`](https://source.chromium.org/chromium/chromium/src/+/main:net/socket/ssl_client_socket_impl.cc;l=906;drc=8e78783dc1f7007bad46d657c9f332614e240fd8?q=VerifyCertCallback&ss=chromium)). 

In [`boringssl/ssl/encrypted_client_hello.cc : 713`](https://source.chromium.org/chromium/chromium/src/+/main:third_party/boringssl/src/ssl/encrypted_client_hello.cc;l=713) (The code I pasted before). The random padding length of ECH extension field can be short enough to cause padding in TLS ClientHello Packet which will make the count of extensions to 17 and change the JA4_c value.

**Comment by fwilliamhe** [comment]
> @fwilliamhe Thanks for the feedback.
> 
>     1. Please help me understand what exactly is not right.
>        i. Is it [JA4 specification](https://github.com/FoxIO-LLC/ja4/blob/f6a1aaa366c964502d0beef17d48e6c7b1aba20d/technical_details/JA4.md)?
>        ii. [Python application](https://github.com/FoxIO-LLC/ja4/tree/f6a1aaa366c964502d0beef17d48e6c7b1aba20d/python)?
>        iii. [Wireshark plugin](https://github.com/FoxIO-LLC/ja4/tree/f6a1aaa366c964502d0beef17d48e6c7b1aba20d/wireshark)?
>        iv. [Rust application](https://github.com/FoxIO-LLC/ja4/tree/f6a1aaa366c964502d0beef17d48e6c7b1aba20d/rust/ja4)?
> 
>     2. Do you have any capture file that can be used to reproduce the problem?
> 
> 
> Thank you.

Thanks for your reply !

The JA4+ Fingerprints of Google Chrome or Chromium (ECH) can be [JA4: t13d1517h2_8daaf6152771_b1ff8ab2d16f], which is different from the one showed in README. 
This happens very rarely and I forgot to save the capture file yesterday. I will try to reproduce it as soon as possible.

As far as I know, this situation happens when no `ECH_Config_List` is given to the SSL socket (Usually because the target server doesn't support ECH) and `ECH_GREASE` will be enabled according to the source of Chromium ([`net/socket/ssl_client_socket_impl.cc:906`](https://source.chromium.org/chromium/chromium/src/+/main:net/socket/ssl_client_socket_impl.cc;l=906;drc=8e78783dc1f7007bad46d657c9f332614e240fd8?q=VerifyCertCallback&ss=chromium)). 

In [`boringssl/ssl/encrypted_client_hello.cc : 713`](https://source.chromium.org/chromium/chromium/src/+/main:third_party/boringssl/src/ssl/encrypted_client_hello.cc;l=713) (The code I pasted before). The random padding length of ECH extension field can be short enough to cause padding in TLS ClientHello Packet which will make the count of extensions to 17 and change the JA4_c value.

**Comment by john-althouse** [comment]
@fwilliamhe Yes, Chrome will have a slightly different JA4 based on if padding is there, which can happen under a couple different circumstances. As well as if pre_shared_key is there which can happen on reconnections. This means Chrome can end up having 6 different JA4s depending on what's going on. Are you suggesting that we ignore padding to reduce the number of fingerprints per application or simply update the example list?

I'm open to ignoring padding but fear it may reduce JA4's effectiveness with other applications slightly.

**Comment by fwilliamhe** [comment]
> @fwilliamhe Yes, Chrome will have a slightly different JA4 based on if padding is there, which can happen under a couple different circumstances. As well as if pre_shared_key is there which can happen on reconnections. This means Chrome can end up having 6 different JA4s depending on what's going on. Are you suggesting that we ignore padding to reduce the number of fingerprints per application or simply update the example list?
> 
> I'm open to ignoring padding but fear it may reduce JA4's effectiveness with other applications slightly.

Sorry for late.

Thanks for replying! I prefer simply updating the example list because I use JA4 to anti spam information so that it's good to keep "the strict rules".

**Comment by 776998428** [comment]
So if I want to get all ja4 fingerprints of chrome, what should I do? For example, my target server is nginx. How do I set up nginx, and then use chrome 120 to access the target server and extract all ja4 fingerprints of chrome 120.

**Comment by john-althouse** [comment]
@fwilliamhe Please see the ja4db.com

@776998428 Please see the JA4 module for nginx

Closing this out.
