### ISSUE TITLE
issue with helper.zeek script

### ISSUE THREAD

**Issue by danielwazhere** [FoxIO-LLC/ja4#33]
Original Code: bad for loop

 local no_grease_comp_methods: index_vec = vector();
  for (idx, val in **no_grease_comp_methods**) {
    if (val !in FINGERPRINT::TLS_GREASE_TYPES) {
      no_grease_comp_methods += val;
    }
  }
  
  recommended change:
  
   local no_grease_comp_methods: index_vec = vector();
  for (idx, val in **comp_methods**) {
    if (val !in FINGERPRINT::TLS_GREASE_TYPES) {
      no_grease_comp_methods += val;
    }
  }

**Comment by john-althouse** [comment]
Fixed, thank you!
