### ISSUE TITLE
JA4SSH Wireshark Plugin Counting SYNACK and PSHACK as ACKs

### ISSUE THREAD

**Issue by john-althouse** [FoxIO-LLC/ja4#36]
JA4SSH_c is supposed to be a count of the bare ACK packets, that is, TCP packets with no payloads and only the ACK flag set. At least in the Wireshark plugin, it looks like it's counting SYN ACKs and PSH ACKs which it shouldn't, just ACKs.

We should also double check the python and rust plugins.

**Comment by noeltimothy** [comment]
This has been fixed in both wireshark and python
