### ISSUE TITLE
JA4H should be case-sensitive only for "Cookie" and "Referer" fields

### ISSUE THREAD

**Issue by noeltimothy** [FoxIO-LLC/ja4#42]
When computing JA4H, we need to relax sesitivity oon the "Cookie" and "Referer" fields present  in the HTTP headers.
All other header fields and values should be case-sensitive.

**Comment by john-althouse** [comment]
So when recording the headers, they should be recorded case sensitive, but when looking for "Cookie" and "Referer" the search for those headers should be case insensitive.

**Comment by noeltimothy** [comment]
Yes John, got it.
