### ISSUE TITLE
Appending JA4 to ssl.log

### ISSUE THREAD

**Issue by HodF-CYE** [FoxIO-LLC/ja4#47]
It was mentioned that by default JA4 sum should be added to the ssl.log file.
It seems that the script is creating a new file "ja4.log", is there a possibilty to add the script output to ssl.log?

**Comment by Hod-CYE** [comment]
When I've cloned the zeek script directly from the repo a "ja4" field has been created.
I assume that zkg.meta should be fiexd..

**Comment by john-althouse** [comment]
@HodF-CYE All of JA4+ is finally done. Unfortunately, there's multiple "ja4" zeek repos in zeek/packages so the correct way to install via zkg is:
```zkg install zeek/foxio/ja4```
This will also get you all of JA4+ instead of just JA4
