### ISSUE TITLE
Python JA4 is not ignoring GREASE in the signature algorithms extension 

### ISSUE THREAD

**Issue by john-althouse** [FoxIO-LLC/ja4#60]
GREASE values should be ignored everywhere they are seen in the TLS client and server hello packets.

**Comment by vvv** [comment]
> they are seen in the TLS client and server hello packets

@john-althouse Do you have any capture file that exposes this?

**Comment by noeltimothy** [comment]
I just saw these unkown values in the "tls-alpn-h2.pcap"
Wireshark shows 0xeeee, 0xefef and 0xeded as unknown.
Should we consider these Gease values?

![image](https://github.com/FoxIO-LLC/ja4/assets/21762538/e5946302-1589-45b0-bc27-ce573bba0e7d)

**Comment by john-althouse** [comment]
Those are not in any RFC I can find. Do you know what application it was? I'm curious to see if those fields change from hello to hello or if they're static for that application.

**Comment by noeltimothy** [comment]
I obtained this pcap from the arkime test pcaps. Don't know how they generated this.

**Comment by awick** [comment]
I'm pretty sure back in 2020 i just used either curl, chrome or some tool that could do h2 to test while I was implementing support.

Something you might want to do is track where you get your PCAP files from, we currently just track ones that we didn't generate, but maybe we should track all for this reason. :) 

Example:
https://github.com/arkime/arkime/blob/main/tests/README

**Comment by john-althouse** [comment]
OK, do not ignore those and just stick to GREASE. Those are most likely programming errors in the application which are the best for fingerprinting.
