### ISSUE TITLE
Nginx submodule not working as expected 

### ISSUE THREAD

**Issue by hugojcqs** [FoxIO-LLC/ja4#92]
Hello,

Not sure this is the place, but the original issue was not addressed for a while on the Nginx submodule git. (https://github.com/FoxIO-LLC/ja4-nginx-module/issues/1)

The problem being that not all fields are filled as exposed by the following screenshot (built witch docker buildx, all branches and release tested):

![image](https://github.com/FoxIO-LLC/ja4/assets/20521391/90b9f9e2-d8b1-4bfb-aa4e-7892d785fa6b)

Could you help on this issue or provide direction to help me resolve it ? I did some digging but was unable to find a solution, I will for sure make a pull request if I manage to correct this.

Kr,

**Comment by john-althouse** [comment]
We are actively working on getting all of JA4+ into nginx for multiple projects. Right now it's just JA4. @ThatcherT can provide an update.

**Comment by ThatcherT** [comment]
@hugojcqs @john-althouse closing this as it is being addressed on the submodule repository https://github.com/FoxIO-LLC/ja4-nginx-module/issues/1#issuecomment-2041705543.

We'll provide updates as they come in!
