### ISSUE TITLE
JA4S Zeek TLS_VERSION_MAPPER Invalid TLS Code(s) issue/fix

### ISSUE THREAD

**Issue by danielwazhere** [FoxIO-LLC/ja4#99]
A little backstory, I'm currently testing this on 3 different corelights between versions 27.9.6 - 27.10.7

I found an issue regarding line 108 of the JA4S **main.zeek** script:
local version = FINGERPRINT::TLS_VERSION_MAPPER[c$fp$server_hello$version];

Testing this with live traffic lead to discovering an issue handling invalid TLS versions. Which seems to be common in some customer environments.

The problem being if an invalid TLS version is found, which would obviously not appear in the TLS_VERSION_MAPPER table inside the **ssl-consts.zeek** script, the custom package/bundle/policy will eventually fail in corelight and quit populating the newly added JA4 fields. 

I hand-jammed the most common invalid TLS codes into the script, such as "0" and some less common DTLS codes for safe measure and this has temporarily fixed it, but without any way to handle invalid TLS codes without needing to explicitly state them in the table this package will inevitably fail again.

May I propose incorporating a way to handle invalid TLS codes within the JA4S main.zeek script in a future update to avoid the package failing again? 

Thank you.

**Comment by john-althouse** [comment]
The spec says that invalid or unknown TLS/SSL versions should be represented with a "00", so basically `else = "00"` But that's not what's happening, so this is bug.

Will get this fixed. Thanks for bringing it up!

**Comment by john-althouse** [comment]
This should have been fixed with pull #100 Let me know if not.
